{{if .Values.kafkaServiceAccount.enabled}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafkasa
  namespace: confluent
spec:
  encryptedData:
    plain.txt: AgBvOkTKKJ9wl0lqA7lYGqSvrcocvX11gKmTASZOMUNEKie1Q5oOihHkSURjk7p3WRcw/trVvRvWsoC0zJqPSLcJPe4MX78yzHZ+AQNdObcbXQg8GtkxutP6FfOhvl/ng+NBpxIZXAuQqIWGKuJrXkmXFvGHvhxuxaQYAbPkiScOMK2NnKDIa7rQ4TkDBBwBuYC4cyTv1QbWeMlDWDngK6ruY5vTHIAsvPbVuYPyUNbVI/aBa+/oWVHSDXdC6wZf7y+PsHklGzewmCgykhvfQsiVQIwTHKfAxRHGrJSNVyoXiF26dI0a1YtwkAjFjb/Lpe7456w5QJHQ69dd3nrdF/Y8FfwO5PWlQxd/vv1yNAzMLSYS7xiWy5KLf55/SvPQJJ3hqBSx6S+IGZQHCAu2Tz8VdEGpF+wJpRw8qXrR4wTofifbeWrcWpPSr/ayQVBWM1vTfJQmg6YEJVacP1ncnaNcGGll5DQZBlJpkuzyFllEAJ6V8dHPzoP3BQzylxgL78ni9lghldVs5TgNwPeJaNVfzyXDW4jTAGl4Hc0lqZF+l9L3EkRBlkki7MvwrmZm+HHeKuW2xC7e2jRcAvdfklO3MdyM9rPODAl9oCJ7F5I4KERRTcLi8Tw+VDEdcMbEIzPilBRBKE5kdtr7LYf3VQvZnrZPrnqmWgzMvIlxp33nc+a4Tx+XoGgoBvMYxj2G790Vj4dagysebUFzBktbNCykfQUyLQH0LOh20Q/JRVb9zpe5f74=
  {{- range .Values.serviceAccounts }}
    {{ .name }}: {{.secret}}
  {{- end}}
  template:
    metadata:
      name: kafkasa
      namespace: confluent
    data:
      plain-users.json: |
        {    
            {{- $first := true -}}
            {{- range $i :=  .Values.serviceAccounts -}}              
              {{- if $first -}}
                  {{- $first = false -}}
              {{- else -}}
                  ,
              {{- end -}}          
              "{{$i.name }}":{{`"{{- index .`}} "{{$i.name -}}"{{` -`}}{{`}}"`}}
            {{- end -}}
        }
{{ end }}      