{{if .Values.kafkaServiceAccount.enabled}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kafkasa
  namespace: confluent
spec:
  encryptedData:
  {{- range .Values.serviceAccounts }}
    {{ .name }}: {{.secret}}
  {{- end}}
  template:
    metadata:
      name: kafkasa
      namespace: confluent
    data:
      plain-users.json: -|
        {
            {{- range $i :=  .Values.serviceAccounts }} 
              "{{$i.name }}":{{`"{{ index .`}} "{{ $i.name }}" {{`}}",`}} 
            {{- end -}}
        }
{{ end }}      