{{if .Values.schemaRegistry.enabled}}
{{- range $path, $d := $.Files.Glob (printf "%s/**.**" .Values.schemasDirectory) }}
apiVersion: v1
kind: ConfigMap
metadata:
{{- $cleanExtension := $path | regexFind "(?:[^/]+/){3}([^/.]+)" }}
{{- $splitString := $cleanExtension | split "/" }}
  name: schema-config-{{$splitString._3}}
  namespace: confluent
data:
  schema: |
  {{- $d | toString | nindent 4 }}
---
{{ end }}
{{ end }}