{{if .Values.schemaRegistry.enabled}}
{{ range $channel := .Values.channels }}
apiVersion: platform.confluent.io/v1beta1
kind: Schema
metadata:
{{- if $channel.subscribe }}
  name: {{$channel.subscribe.message.name}}-value
{{- else }}
  name: {{$channel.publish.message.name}}-value
{{- end }}
  namespace: confluent
spec:
  data:
  {{- if $channel.subscribe }}
    configRef: schema-config-{{$channel.subscribe.message.name}}-value
    format: {{$channel.subscribe.message.contentType}}
  {{- else }}
    configRef: schema-config-{{$channel.publish.message.name}}-value
    format: {{$channel.publish.message.contentType}}
  {{- end }}
---
{{ end }}
{{ end }}