{{ range $channel := .Values.channels }}
apiVersion: v1
kind: ConfigMap
metadata:
{{- if $channel.subscribe }}
  name: lower schema-config-{{$channel.subscribe.message.name}}
{{- else }}
  name: lower schema-config-{{$channel.publish.message.name}}
{{- end }}
  namespace: confluent
{{- if $channel.subscribe }}
data:
  {{- range $path, $d := $.Files.Glob "{{.Values.schemasDirectory}}/**.**" }}
  {{ $path }}: |-
  {{- $d | toString | nindent 4 }}
  {{ end }}
{{- else }}
data:
  {{- range $path, $d := $.Files.Glob "{{.Values.schemasDirectory}}/**.**" }}
  {{ $path }}: |-
  {{- $d | toString | nindent 4 }}
  {{ end }}
{{- end }}
---
{{ end }} 