{{ range $channel := .Values.channels }}
apiVersion: v1
kind: ConfigMap
metadata:
{{- if $channel.subscribe }}
  name: schema-config-{{$channel.subscribe.message.name}}
{{- else }}
  name: schema-config-{{$channel.publish.message.name}}
{{- end }}
  namespace: confluent
data:
  schema: |-
    {{ .Files.Get "./schemas/product_created.avsc" | indent 4 }}
---
{{ end }} 